services:
  - type: web
    name: qr-sharing-web
    env: node
    buildCommand: npm install
    startCommand: npm run start:prod
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FILE_EXPIRY_DAYS
        value: 7
      - key: MAX_FILE_SIZE
        value: 52428800
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: qr-sharing-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
